on:
  push:
    branches:
      - main
      - develop
    paths:
      - backend/**
name: Linux_Container_Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - name: Branch name
        run: echo running on branch ${{ github.ref_name }}
      # Upgrade java version from 11 to 17
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_PATH }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          cd backend
          mvn package -DskipTests
          docker build -f src/main/docker/Dockerfile.jvm -t ${{ secrets.REGISTRY_PATH }}/volcampanion-api:${{ github.ref_name }} .
          docker push ${{ secrets.REGISTRY_PATH }}/volcampanion-api:${{ github.ref_name }}
